### ISSUE TITLE
Data review

### ISSUE THREAD

**Issue by andrew-hipp** [andrew-hipp/prairie-biomass-2018#1]
Lane and Ashley should review the datasets, make sure they like what's in there. 
Are there more recent NDVI or biomass needed?

**Comment by lanescher** [comment]
I have lots more data, but I'm not sure what to add.

Should I just add a file to the DATA folder with the VI values that I have pulled from the VI rasters? Or should I upload the rasters and the code that produces the VI values and write them to the DATA folder? I'm guessing the latter, especially because the rasters might change.

**Comment by lanescher** [comment]
Ok, I have the calibrated rasters (finally!!!!), but they are too large to upload to github. I will get the data out of them that I think we want to analyze and just add that.

**Comment by altuffin** [comment]
Recent NDVI and other VIs added and included in 'all.praire'

**Comment by andrew-hipp** [comment]
It looks as though all data are now current. I'm closing this issue as a consequence.
