### ISSUE TITLE
Script sequence and calling

### ISSUE THREAD

**Issue by andrew-hipp** [andrew-hipp/prairie-biomass-2018#10]
Right now, scripts are approximately in order, but calling each other multiple times. This needs to be pulled out, and one master script written that calls them sequentially

**Comment by lanescher** [comment]
I will: 
-Add if statement to only run analysis of tifs if necessary. -- or just comment it out
-check size of tif files, send to Andrew for storage so we can all access them
-export results of analysis and save it to the repository

**Comment by lanescher** [comment]
I have gone through all the scripts and I think this order makes sense. I will rename them to follow this order unless either of you see a problem. Then I will write a master script that calls everything in sequence, but comment out the lines that call for new VI calculations (that step is pretty slow).

01.make.plot.polygons
00a.compileData
00b.readData.biomassPlotsTree-v2
00c.problemSpp.2017
102.define.VI.functions
103.calculate.VI.things (this script requires data that is read in in 00a. I made a new script that compiles the df produced in this script with the df produced in 00a.)
03.sensitiveEnvir
107.add.VIdata.to.all.prairie
------ at this point, all the data should be read in and formatted into one df called all.prairie ------

The rest seems to be less order-sensitive, but correct me if I'm wrong. This is an order that seemed to make sense to me:
04a.phylo.v3
04b.phyloSignal
05.traitNDVI.biomass
07.biomass&VI.model.ahor&block
104c.make.regression.summary.table.biomass
105c.make.regression.summary.table.cover
106.making.graphs
999.gheatmap.mod

Some scripts (listed below) are outdated. I moved them to the ARCHIVE folder because they don't produce any output that is needed for analyses or figures. I can pull them back out if we need.
103old.calculate.VI.things.deleted.lines
104.predicting.biomass.from.VIs.and.cover
104b.predicting.biomass.from.VIs.and.cover.correct.plots.only
105.predicting.cover.from.VIs
