### ISSUE TITLE
Sequence of VIs

### ISSUE THREAD

**Issue by andrew-hipp** [andrew-hipp/prairie-biomass-2018#13]
Currently, VIs appear to be calculated in scripts 102ff, yet we are referencing them in scripts 4 and 5. This is confusing. Because VIs are integral to this study, they need to be cleaned up at the beginning so that we are using one set of VIs throughout.

At this point, I'm not even sure whether I am using the right things for the phylogeny figure and ordination. We need to look at this together and figure out how they can be sequenced and cleaned up, then when the data are organized, I can revised the phylogeny and ordination scripts (if needed) to use the correct data.

**Comment by lanescher** [comment]
I will:
-move VI calculations so it happens earlier
-make sure the correct VI values are in alldata df

**Comment by lanescher** [comment]
This is done. The correct VI values are calculated in script 103, stored in a csv called VIdata.csv, and added to all.prairie in 107.

The VI data has to be calculated after the rest of the data is compiled because it requires some of the data from all.prairie.

All outdated VI data has been removed from all.prairie object. It is still stored in a .csv called VIvalues-old.csv and in all.prairie.with.VIvalues-old.csv

**Comment by lanescher** [comment]
See issue "script sequence and calling" regarding where I want to put this script in the sequence of scripts.

Closing this issue.
